### ISSUE TITLE
Resolution for 6.5 Screen

### ISSUE THREAD

**Issue by joroge** [nerone-github/WebViewAuto#4] opened 2018-01-02 07:53 UTC
Hi, the resoluttion for 6.5 screen isn´t correct. Can´t see the keyboard complete.

**Comment by nerone-github** [comment] 2018-01-02 08:05
Hi, what car is it? I have too 6.5" and it works fine? Can you make screenshot/photo please?

**Comment by joroge** [comment] 2018-01-02 18:46
Video bug: https://drive.google.com/a/binaryship.com/file/d/1RsrTvTgNham1BhCkHPRkQFBCVaUmc2Jw/view?usp=drivesdk

It's Seat Leon with MIB2

**Comment by nerone-github** [comment] 2018-01-02 18:48
The link does not work, please change permission to public

**Comment by joroge** [comment] 2018-01-02 20:39
Sorry!!

This link:

https://drive.google.com/file/d/1ImkHGFsz0m53yvzucsImMCPQFczWL_Jg/view?usp=drivesdk

**Comment by nerone-github** [comment] 2018-01-02 20:41
Hm okay this seems to be something phone-dependent for sure. What Android version? Vendor? It seems that the margin of the keys is a lot larger than expected for you

**Comment by joroge** [comment] 2018-01-03 07:16
The phone is Huawei Honor 6. Android Version 6.0.1

**Comment by nerone-github** [comment] 2018-01-03 09:41
Can you retry with the latest APK please?

**Comment by nerone-github** [comment] 2018-01-06 19:28
Any news? Worked or still no ?

**Comment by UrosJan** [comment] 2018-01-07 16:02
Hello... I got in my Octavia 3 pioneer avic evo head unit and work ok. 

only on youtube on mobile version cant write on search line because is no keyboard options... on desktop version is ok.
why is video not play on full screen? 

and why is no option to fit page on screen... page on browser is bigest than that screen. 

Any way thaks for this apps....

**Comment by nerone-github** [comment] 2018-01-08 20:04
Duplicate of #5

**Closed by nerone-github** 2018-01-08 20:04 UTC
Labels: bug
