### ISSUE TITLE
Whatsapp Web

### ISSUE THREAD

**Issue by kaisertgc** [nerone-github/WebViewAuto#16] opened 2018-01-19 08:40 UTC
Hi,
On whatsapp web when I put message, it doesnt recognize the text and send button doesnt appear.

And to send voice message it is asking microphone permissions. Is it possible? It would be nice to send voice messages while driving.

Thanks.

**Comment by nerone-github** [comment] 2018-01-19 08:43
Using the latest build? With it it should work. The Voice stuff is something for a separate issue.

**Comment by nerone-github** [comment] 2018-01-19 08:44
Also the real issue for this problem is actually #14 so this is a Duplicate of #14 technically

**Closed by nerone-github** 2018-01-19 08:44 UTC

**Comment by kaisertgc** [comment] 2018-01-19 08:48
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)

**Comment by kaisertgc** [comment] 2018-01-19 08:49
Understood thanks)
